### ISSUE TITLE
conda 环境下，切换环境后持续 warning 无法触发补全

### ISSUE THREAD

**Issue by C1tas** [xhcoding/ms-python#3]
你好，我希望获得一点使用上的帮助

![image](https://user-images.githubusercontent.com/16471247/54004615-277bd100-4191-11e9-9179-86f8174b70d8.png)

![image](https://user-images.githubusercontent.com/16471247/54004653-585c0600-4191-11e9-829e-6f44e7566df1.png)

平台 macos 10.13.6 (17G5019)
emacs 
![image](https://user-images.githubusercontent.com/16471247/54004680-76c20180-4191-11e9-9787-4a8a8395550d.png)

**Comment by xhcoding** [comment]
服务端新加了三个自定义的方法，用于报告服务端处理状态。我直接忽略了，现在应该没问题了。
